# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding never settle
email: cyhaocn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Changying Hao, I am currently a intern
  in Institute of Computing Technology, Chinese Academy of Sciences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cyhao.me" # the base hostname & protocol for your site
twitter_username: cyhaocn
github_username:  ying-A

# Build settings
markdown: kramdown

theme: jekyll-theme-architect
